FROM node:20-bookworm-slim
LABEL authors="Kit Plummer <kit@ditto.live>"

WORKDIR /app

COPY start_node.sh /app/
COPY package*.json /app/
COPY dist /app/dist

# update each dependency in package.json to the latest version
RUN npm install && npm cache clean --force && chmod +x /app/start_node.sh
ENTRYPOINT ["/app/start_node.sh"]
CMD ["autov"]
