
name: Labels all issues and adds to project board
on: pull_request
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:

      - name: Get project data
        env:
          GH_TOKEN: ${{ secrets.ISSUE_LABEL_PAT }}
          ORGANIZATION: getditto
          PROJECT_NUMBER: 30

        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          # Parses the response from the API query and stores the relevant IDs as
          # environment variables. Modify this to get the ID for different fields or
          # options.
          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_OPTION='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="Backlog") |.id' project_data.json) >> $GITHUB_ENV
          echo 'PROJECT_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Project") | .id' project_data.json) >> $GITHUB_ENV
          echo 'PROJECT_OPTION='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Project") | .options[] | select(.name=="Polaris") |.id' project_data.json) >> $GITHUB_ENV

      - name: Add PR to project
        env:
          GH_TOKEN: ${{ secrets.ISSUE_LABEL_PAT }}
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          item_id="$( gh api graphql -f query='
            mutation($project:ID!, $pr:ID!) {
              addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f pr=$PR_ID --jq '.data.addProjectV2ItemById.item.id')"

            echo 'ITEM_ID='$item_id >> $GITHUB_ENV

      - name: Set issue Status field for github projects
        env:
          GH_TOKEN: ${{ secrets.ISSUE_LABEL_PAT }}
        run: |
          OPTION_STR="${{ env.STATUS_OPTION }}"
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $fieldId: ID!
              $fieldOption: String!
            ) {
              set_status: updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $fieldId
                value: {
                  singleSelectOptionId: $fieldOption
                  }
              }) {
                projectV2Item {
                  id
                  }
              }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f fieldId=$STATUS_FIELD_ID -f fieldOption=$OPTION_STR

      - name: Set issue Project field
        env:
          GH_TOKEN: ${{ secrets.ISSUE_LABEL_PAT }}
        run: |
          OPTION_STR="${{ env.PROJECT_OPTION }}"
          gh api graphql -f query='
            mutation (
              $project: ID!
              $item: ID!
              $fieldId: ID!
              $fieldOption: String!
            ) {
              set_status: updateProjectV2ItemFieldValue(input: {
                projectId: $project
                itemId: $item
                fieldId: $fieldId
                value: {
                  singleSelectOptionId: $fieldOption
                  }
              }) {
                projectV2Item {
                  id
                  }
              }
            }' -f project=$PROJECT_ID -f item=$ITEM_ID -f fieldId=$PROJECT_FIELD_ID -f fieldOption=$OPTION_STR
